pub use cshake::*;

cshake_customs! {
    "__bcsp__"
    DSA_SK_DERIVE
    DSA_XSIGN_HASH
    DSA_EDSIGN_R_HASH
    DSA_EDSIGN_K_HASH
    DH_SK_GEN_PRNG
    HANDSHAKE_PRE_MASK
    HANDSHAKE_CIPHER
    REQ_KEY_DERIVE
    FRAME_HEADER_CIPHER
    FRAME_PAYLOAD_CIPHER
    FRAME_HEADER_MAC
    FRAME_PAYLOAD_MAC
}
